# AWS RDS connection
spring.datasource.url=jdbc:postgresql://skillmap-postgres.cvc2ueqgkc5p.ap-south-1.rds.amazonaws.com:5432/skillmapdb
spring.datasource.username=skillmap
spring.datasource.password=SkillMap2024!
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080